# Generated by Django 3.1 on 2020-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200812_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='Donde vives'),
        ),
    ]
